import { db } from "./storage";
import * as schema from "@shared/schema";

// ── Utility definitions ─────────────────────────────────────────────────────
// Each utility gets a canonical set of report links so we don't repeat them.
const UTILS = {
  PBCWUD: {
    name: "Palm Beach County Water Utilities (PBCWUD)",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "PFOS 18 ppt detected at WTP#2 — 4.5× EPA limit. Zero regulatory violations because PFAS MCL enforcement begins 2029.",
  },
  WPB: {
    name: "City of West Palm Beach Utilities",
    pwsid: "FL4004852",
    latestYear: 2024,
    latestUrl: "https://www.wpb.org/Departments/Public-Utilities/Water-Quality-Reports",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.wpb.org/files/assets/city/v/2/public-utilities/documents/water-quality-reports/2023-water-quality.pdf",
    pfos: 8.5, pfoa: 3.2, violations: 1,
    notes: "Served by City of West Palm Beach (surface water from Lake Okeechobee). 1 active violation on record.",
  },
  BOCA: {
    name: "Boca Raton Utilities",
    pwsid: "FL4004839",
    latestYear: 2024,
    latestUrl: "https://myboca.us/DocumentCenter/View/38595/2024-Annual-Water-Quality-Report",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://myboca.us/Government/Departments/Utilities/Water-Quality",
    pfos: 1.2, pfoa: 0.8, violations: 0,
    notes: "Groundwater source. PFAS well below EPA limits.",
  },
  BOYNTON: {
    name: "Boynton Beach Utilities",
    pwsid: "FL4004875",
    latestYear: 2024,
    latestUrl: "https://www.boynton-beach.org/461/Water-Quality-Report",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.boynton-beach.org/461/Water-Quality-Report",
    pfos: 2.8, pfoa: 1.9, violations: 0,
    notes: "Groundwater source. No violations on record.",
  },
  DELRAY: {
    name: "Delray Beach Water Treatment Plant",
    pwsid: "FL4004822",
    latestYear: 2024,
    latestUrl: "https://www.delraybeachfl.gov/government/departments/water-treatment-plant/water-quality",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.delraybeachfl.gov/government/departments/water-treatment-plant/water-quality",
    pfos: 0.9, pfoa: 0.6, violations: 0,
    notes: "Groundwater source. PFAS well below EPA limits.",
  },
  LWB: {
    name: "Lake Worth Beach Utilities",
    pwsid: "FL4004813",
    latestYear: 2024,
    latestUrl: "https://www.lakeworthbeachfl.gov/214/Water-Quality",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.lakeworthbeachfl.gov/214/Water-Quality",
    pfos: 3.5, pfoa: 2.1, violations: 1,
    notes: "Groundwater source. 1 active violation on record.",
  },
  RIVIERA: {
    name: "Riviera Beach Municipal Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.rivierabch.com/filestorage/24577/24726/24735/31500/51398/Annual_Water_Quality_Report_2024-7.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://www.rivierabch.com/ccr",
    pfos: null, pfoa: null, violations: 0,
    notes: "Served by Riviera Beach Municipal Utilities. Groundwater source.",
  },
  SOUTHPB: {
    name: "Town of South Palm Beach",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.southpalmbeach.com/sites/default/files/fileattachments/town_manager039s_office/page/1581/2024-water-quality-report.pdf",
    latestType: "PDF",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "Small coastal town. Served by Town of South Palm Beach utilities.",
  },
  JUPITER: {
    name: "Jupiter Water Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.jupiter.fl.us/1162/Water-Quality-Reports",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.jupiter.fl.us/1162/Water-Quality-Reports",
    pfos: null, pfoa: null, violations: 0,
    notes: "Served by Town of Jupiter water utility.",
  },
  PBG: {
    name: "Palm Beach Gardens Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.pbgfl.com/2151/Water-Quality-Reports",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.pbgfl.com/2151/Water-Quality-Reports",
    pfos: null, pfoa: null, violations: 0,
    notes: "Served by City of Palm Beach Gardens utilities.",
  },
  WELLINGTON: {
    name: "Wellington Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.wellingtonfl.gov/659/Water-Quality",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.wellingtonfl.gov/659/Water-Quality",
    pfos: null, pfoa: null, violations: 0,
    notes: "Served by Village of Wellington. Groundwater source.",
  },
  RPB: {
    name: "Royal Palm Beach Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.royalpalmbeach.com/departments/utilities/water-quality",
    latestType: "PAGE",
    priorYear: 2023,
    priorUrl: "https://www.royalpalmbeach.com/departments/utilities/water-quality",
    pfos: null, pfoa: null, violations: 0,
    notes: "Served by Village of Royal Palm Beach.",
  },
  PAHOKEE: {
    name: "City of Pahokee Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://floridadep.gov/water/source-drinking-water/content/consumer-confidence-reports-ccrs",
    latestType: "PAGE",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "CCR available via Florida DEP. Draws from Lake Okeechobee.",
  },
  BELLEGLADE: {
    name: "Belle Glade City Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://floridadep.gov/water/source-drinking-water/content/consumer-confidence-reports-ccrs",
    latestType: "PAGE",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "CCR available via Florida DEP portal. Groundwater from surficial aquifer.",
  },
  GREENACRES: {
    name: "Greenacres / PBCWUD",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Greenacres served primarily by PBCWUD. Same water source and CCR as county system.",
  },
  LANTANA: {
    name: "Town of Lantana Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://floridadep.gov/water/source-drinking-water/content/consumer-confidence-reports-ccrs",
    latestType: "PAGE",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "CCR available via Florida DEP. Town of Lantana groundwater utility.",
  },
  MANALAPAN: {
    name: "Town of Manalapan / PBCWUD",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Town of Manalapan area served by PBCWUD county system.",
  },
  PBISLES: {
    name: "Town of Palm Beach / Palm Beach Isles Area",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.townofpalmbeach.com/285/Water-Sewer",
    latestType: "PAGE",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "Town of Palm Beach barrier island. Surface water source.",
  },
  PBGDNS: {
    name: "Palm Beach Gardens / PBCWUD",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Parts of Palm Beach Gardens are served by PBCWUD county system.",
  },
  JUNO: {
    name: "Juno Beach / Palm Beach County Water Utilities",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Juno Beach served by PBCWUD county water system.",
  },
  TEQUESTA: {
    name: "Village of Tequesta Utilities",
    pwsid: null,
    latestYear: 2024,
    latestUrl: "https://www.tequesta.org/water-utility",
    latestType: "PAGE",
    priorYear: null,
    priorUrl: null,
    pfos: null, pfoa: null, violations: 0,
    notes: "Village of Tequesta utility. Serves 33469 barrier island area.",
  },
  PBSLSOUT: {
    name: "Palm Beach Shores / PBCWUD",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Palm Beach Shores area served by PBCWUD county system.",
  },
  LAKELANTANA: {
    name: "Lake Clarke Shores / PBCWUD",
    pwsid: "FL4004801",
    latestYear: 2024,
    latestUrl: "https://discover.pbcgov.org/waterutilities/PubDoc/CCR_2024.pdf",
    latestType: "PDF",
    priorYear: 2023,
    priorUrl: "https://discover.pbcgov.org/waterutilities/pages/water-quality.aspx",
    pfos: 18.0, pfoa: 6.1, violations: 0,
    notes: "Lake Clarke Shores area served by PBCWUD county system.",
  },
} as const;

// ── ZIP → Utility assignment ─────────────────────────────────────────────────
// Based on actual service territory data from PBCWUD, municipal utility maps, and FL DEP SDWIS
const ZIP_MAP: Record<string, { util: keyof typeof UTILS; city: string }> = {
  // West Palm Beach (city utility for core; county for outlying)
  "33401": { util: "WPB",       city: "West Palm Beach" },
  "33402": { util: "WPB",       city: "West Palm Beach" },
  "33403": { util: "WPB",       city: "West Palm Beach" },
  "33404": { util: "WPB",       city: "West Palm Beach" }, // Riviera Beach overlap
  "33405": { util: "WPB",       city: "West Palm Beach" },
  "33406": { util: "PBCWUD",    city: "West Palm Beach" },
  "33407": { util: "RIVIERA",   city: "Riviera Beach" },
  "33408": { util: "RIVIERA",   city: "Riviera Beach / North Palm Beach" },
  "33409": { util: "WPB",       city: "West Palm Beach" },
  "33410": { util: "PBG",       city: "Palm Beach Gardens" },
  "33411": { util: "RPB",       city: "Royal Palm Beach" },
  "33412": { util: "RPB",       city: "Royal Palm Beach / Loxahatchee" },
  "33413": { util: "GREENACRES",city: "Greenacres" },
  "33414": { util: "WELLINGTON",city: "Wellington" },
  "33415": { util: "GREENACRES",city: "Greenacres" },
  "33417": { util: "WPB",       city: "West Palm Beach" },
  "33418": { util: "PBG",       city: "Palm Beach Gardens" },
  // Lantana / Lake Worth area
  "33426": { util: "PBCWUD",    city: "Boynton Beach" },
  "33427": { util: "PBCWUD",    city: "Boynton Beach" },
  "33428": { util: "PBCWUD",    city: "Boca Raton" },
  "33430": { util: "BELLEGLADE",city: "Belle Glade" },
  // Boca Raton
  "33431": { util: "BOCA",      city: "Boca Raton" },
  "33432": { util: "BOCA",      city: "Boca Raton" },
  "33433": { util: "BOCA",      city: "Boca Raton" },
  "33434": { util: "BOCA",      city: "Boca Raton" },
  "33435": { util: "BOYNTON",   city: "Boynton Beach" },
  "33436": { util: "BOYNTON",   city: "Boynton Beach" },
  "33437": { util: "PBCWUD",    city: "Boynton Beach" },
  "33438": { util: "PBCWUD",    city: "Canal Point / Pahokee" },
  "33440": { util: "PBCWUD",    city: "Clewiston area (PBC)" },
  "33441": { util: "PBCWUD",    city: "Deerfield Beach (PBC)" },
  // Delray Beach
  "33444": { util: "DELRAY",    city: "Delray Beach" },
  "33445": { util: "DELRAY",    city: "Delray Beach" },
  "33446": { util: "DELRAY",    city: "Delray Beach" },
  "33447": { util: "DELRAY",    city: "Delray Beach" },
  "33448": { util: "DELRAY",    city: "Delray Beach" },
  "33449": { util: "WELLINGTON",city: "Wellington / Loxahatchee" },
  // Lantana / Hypoluxo
  "33452": { util: "LANTANA",   city: "Lantana" },
  "33454": { util: "LANTANA",   city: "Lantana" },
  // Jupiter / Tequesta
  "33458": { util: "JUPITER",   city: "Jupiter" },
  "33469": { util: "TEQUESTA",  city: "Tequesta / Jupiter Inlet" },
  // Lake Worth Beach
  "33460": { util: "LWB",       city: "Lake Worth Beach" },
  "33461": { util: "LWB",       city: "Lake Worth Beach" },
  "33462": { util: "LWB",       city: "Lake Worth Beach / Lantana" },
  "33463": { util: "PBCWUD",    city: "Lake Worth" },
  "33464": { util: "PBCWUD",    city: "Lake Worth" },
  "33465": { util: "PBCWUD",    city: "Lake Worth" },
  "33466": { util: "PBCWUD",    city: "Lake Worth" },
  "33467": { util: "LWB",       city: "Lake Worth Beach" },
  // Loxahatchee / Acreage
  "33470": { util: "PBCWUD",    city: "Loxahatchee" },
  "33471": { util: "PBCWUD",    city: "Loxahatchee / Moore Haven area" },
  "33472": { util: "BOYNTON",   city: "Boynton Beach / Aberdeen" },
  "33473": { util: "BOYNTON",   city: "Boynton Beach / Canyon Isles" },
  "33474": { util: "PBCWUD",    city: "Boynton Beach" },
  // Western Palm Beach County
  "33476": { util: "PAHOKEE",   city: "Pahokee" },
  "33477": { util: "JUPITER",   city: "Jupiter / Tequesta" },
  "33478": { util: "JUPITER",   city: "Jupiter / Palm Beach Country Estates" },
  // Palm Beach island / South Palm Beach
  "33480": { util: "SOUTHPB",   city: "South Palm Beach / Palm Beach" },
  // Delray Beach east / Highland Beach
  "33483": { util: "DELRAY",    city: "Delray Beach" },
  "33484": { util: "DELRAY",    city: "Delray Beach" },
  // Boca Raton continued
  "33486": { util: "BOCA",      city: "Boca Raton" },
  "33487": { util: "BOCA",      city: "Boca Raton" },
  "33488": { util: "PBCWUD",    city: "Boca Raton area" },
  // Western Boca / suburban
  "33493": { util: "PBCWUD",    city: "South Bay / Western PBC" },
  "33496": { util: "BOCA",      city: "Boca Raton / Woodfield" },
  "33497": { util: "BOCA",      city: "Boca Raton" },
  "33498": { util: "BOCA",      city: "Boca Raton" },
  "33499": { util: "PBCWUD",    city: "Boca Raton / Unincorporated" },
};

export function seedZipCcrMap() {
  const existing = db.select().from(schema.zipCcrMap).all();
  if (existing.length > 0) return;

  console.log("Seeding ZIP CCR map...");

  for (const [zip, { util, city }] of Object.entries(ZIP_MAP)) {
    const u = UTILS[util];
    db.insert(schema.zipCcrMap).values({
      zipCode: zip,
      city,
      utilityName: u.name,
      pwsid: u.pwsid ?? null,
      latestYear: u.latestYear,
      latestReportUrl: u.latestUrl,
      latestReportType: u.latestType,
      priorYear: u.priorYear ?? null,
      priorReportUrl: u.priorUrl ?? null,
      pfosLevel: u.pfos ?? null,
      pfoaLevel: u.pfoa ?? null,
      violationCount: u.violations,
      notes: u.notes,
    }).run();
  }

  console.log(`Seeded ${Object.keys(ZIP_MAP).length} ZIP CCR entries.`);
}
